### ISSUE TITLE
Error in current version

### ISSUE THREAD

**Issue by petrakohorst** [LibreCat/LibreCat-Frontend-Tests#1]
There seems to be a bug in the current version. I just pulled the latest changes and now I'm getting the following error when I run ```$(npm bin)/cypress open```

```Error: Cannot find module 'he' from '[...]/cypress/support/commands'```

**Comment by verheyenkoen** [comment]
I've added an npm module, so you'll have to re-execute `npm install` (probably a good practice to run this after every pull).

**Comment by verheyenkoen** [comment]
Btw, also make sure to read the README again, as I've added a section on multilingual tests. You'll need to export your LibreCat translations to the tests.

**Comment by petrakohorst** [comment]
Yes, now it's working. Also the English and German versions.

Perfect! Thank you!
