### ISSUE TITLE
Test marking records

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat-Frontend-Tests#2]
- No login is required.
- Click 'publications' tab
- Click first publication title
   - Click mark publication checkbox 
   - The marked records counter (under Export) should say 1 Marked Publications
- Click second publication title
   - Click mark publication checkbox 
   - The marked records counter (under Export) should say 2 Marked Publications
- Click 2 Marked Publications
   - The display should show 2 publications
- With a drag and drop the second publication can be moved above the first one
- Export as 'BibText'
   - An export with  2 publications should be found
- Click on 'unmark all'
   - No publications should be marked

**Comment by verheyenkoen** [comment]
I noticed the BibTeX export does not contain the right order of publications (as drag-and-dropped). Not sure if that is a bug. If it is, reopen this issue and I will extend the test to cover that.
