### ISSUE TITLE
Testing BibText import

### ISSUE THREAD

**Issue by phochste** [LibreCat/LibreCat-Frontend-Tests#3]
- Login as test user
- Click 'Add Publications'
- In Paste Your BibTex records add this text:

```
@article{small,
author = {Freely, I.P.},
title = {A small paper},
journal = {The journal of small papers},
year = 1997,
volume = {-1},
note = {to appear},
}

@article{big,
author = {Jass, Hugh},
title = {A big paper},
journal = {The journal of big papers},
year = 7991,
volume = {MCMXCVII},
}
```
- Click on import
- The title should say:

```
Imported 2 record(s) from bibtex
 A small paper
 A big paper
```

- Clicking on the 'edit' link should open the form to edit the metadata [this fails currently !]

**Comment by verheyenkoen** [comment]
Wrote the test without the last step for now. Notify me when this works and I'll complete it.

Also, I'm not sure whether anything should be cleaned up after this test. I can't find any new publications. If new publications were created, we should remove them again in the teardown.

**Comment by nicolasfranck** [comment]
See https://github.com/LibreCat/LibreCat/issues/324
